### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Jonovono** [hargettp/hh-web#3]
I am very new to lisp development and have been looking to pick up a functional language for web development. Some questions:
1. Can you compare this to weblocks and the other main common lisp web frameworks
2. Why this over other languages like Noir for Clojure, etc.
3. Does this come with support for ajax?

That's all for now. Thanks.

**Comment by hargettp** [comment]
Hi, thanks for your interest in hh-web!

First, a couple of things: while functional programming is quite doable in
Lisp, I would not say that Lisp is itself a functional language.  Further,
I've written hh-web in Common Lisp, a rich dialect of Lisp that really, I
think, makes symbolic programming natural. In some ways, both symbolic and
functional programming are very powerful tools, both suitable as a powerful
foundation for programming;  they are, however, fundamentally different in
their core.

Regarding hh-web specifically and the questions you have asked:

Re weblocks and other frameworks: while I may have lost touch, I am not
aware of too many frameworks that resemble hh-web. Both weblocks and hh-web
come from different places and solve different problems. The former
emphasizes continuation passing style for developing web applications;
hh-web started as a way of solving the classic HTML generation problem
faced by all web frameworks. I extended hh-web to incorporate successful
features that I saw in frameworks such as Django and Rails (eg routing) and
more or less built what I needed as I went.

Re Noir or Clojure: while Clojure has many things to commend it, it is
still bound by the JVM on which it runs.  Common Lisp has many native
implementations (I use SBCL), so I know that my application is running
"close to the metal," without the overhead of a JVM but still having the
full power of Lisp.

Re Ajax : I have used Ajax with hh-web. I had some bits written at one
point to make Ajax a bit easier to use, but I have not yet documented them
or truly published them. Nothing at all prevents the use of Ajax; I just
haven't evolved hh-web to offer any unique features in that area.

I hope some of the above helps, and definitely dive into Lisp—you'll be a
better programmer for it!

:)

On Apr 1, 2013, at 9:28 PM, Jonovono notifications@github.com wrote:

I am very new to lisp development and have been looking to pick up a
functional language for web development. Some questions:
1. Can you compare this to weblocks and the other main common lisp web
   frameworks
2. Why this over other languages like Noir for Clojure, etc.
3. Does this come with support for ajax?

That's all for now. Thanks.

—
Reply to this email directly or view it on
GitHubhttps://github.com/hargettp/hh-web/issues/3
.

**Comment by Jonovono** [comment]
Awesome! Thanks for the quick reply. I will for sure keep following it :) I am going through a few of the different lisp dialects and seeing which one I like the best.
