### ISSUE TITLE
Sample apps?

### ISSUE THREAD

**Issue by Davidbhodge** [hargettp/hh-web#4]
Would there be any sample app written in hh-web? 

Cheers

**Comment by hargettp** [comment]
Well, the best I can offer is the sample created by following the instructions in the README. The generated sample has all the moving parts needed for a fully functional hh-web application. Beyond that, I'd be happy to answer any questions about tips or techniques.

**Comment by Davidbhodge** [comment]
Ok,

I will look into it a little more tonight - and thanks for the quick response.

I am looking into redeveloping a very old, but quite successful application - moving from the pc world onto the web. I was originally thinking of Django, but Lisp  is really my first choice if I can make it stick. The other lisp web frameworks , like weblocks, are either too heavyweight or moribund. This seems pitched at the right level for me I think and I note that it can use Bootstrap which is a win for me.

 I will need ajax, so expect a few questions later if I move forward
